import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../models/history_entry.dart';

class ShareService {
  static Future<void> shareStatistics({
    required int currentCount,
    required int highestCount,
    required int currentStreak,
    required int bestStreak,
    required int increaseCount,
    required int decreaseCount,
    required int resetCount,
  }) async {
    final text = '''
📊 Countify Statistics

🔢 Current Count : $currentCount
🏆 Highest Count : $highestCount

🔥 Current Streak : $currentStreak Day${currentStreak == 1 ? "" : "s"}
⭐ Best Streak : $bestStreak Day${bestStreak == 1 ? "" : "s"}

🟢 Increase : $increaseCount
🔴 Decrease : $decreaseCount
🟠 Reset : $resetCount

Generated by Countify 🚀
''';

    await SharePlus.instance.share(
      ShareParams(
        text: text,
      ),
    );
  }

  static Future<void> shareHistory(List<HistoryEntry> history) async {
    final DateFormat formatter = DateFormat("MMM dd, yyyy - hh:mm a");
    final buffer = StringBuffer();
    buffer.writeln("📜 Countify History Report");
    buffer.writeln("Total Records: ${history.length}");
    buffer.writeln("Generated: ${formatter.format(DateTime.now())}");
    buffer.writeln("----------------------------------\n");

    for (var i = 0; i < history.length && i < 100; i++) {
      final entry = history[i];
      final actionSymbol = switch (entry.action) {
        HistoryAction.increase => "🟢 +",
        HistoryAction.decrease => "🔴 -",
        HistoryAction.reset => "🟠 ↺",
      };
      final timeStr = formatter.format(entry.timestamp);
      buffer.writeln("$actionSymbol [${entry.counterName}] Count: ${entry.count} ($timeStr)");
      if (entry.note != null && entry.note!.isNotEmpty) {
        buffer.writeln("   Note: ${entry.note}");
      }
    }

    if (history.length > 100) {
      buffer.writeln("\n...and ${history.length - 100} more entries.");
    }

    buffer.writeln("\nExported via Countify 🚀");

    await SharePlus.instance.share(
      ShareParams(
        text: buffer.toString(),
      ),
    );
  }

  static Future<void> shareApp() async {
    await SharePlus.instance.share(
      ShareParams(
        text: '''
Try Countify 🚀

A beautiful counter app with History, Statistics, Daily Goals and more.

https://play.google.com/store/apps/details?id=com.your.package.name
''',
      ),
    );
  }
}